title: YesDev Games
description: Yes we dev games
baseurl: '' # the subpath of your site, e.g. /blog
url: yesdev.games

markdown: kramdown
permalink: '/:title/'
excerpt_separator: <!--more-->
gems: [jekyll-paginate]
paginate: 5